name: Lint CSS files

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - '**.css'
            - '**.scss'
            - .github/workflows/lint_css.yml

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    lint-styles:
        permissions:
            contents: read
        runs-on: 'ubuntu-latest'
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/node-npm-setup

            - name: Run linter
              run: npm run lint:css
