name: WPCS check

on: pull_request

jobs:
    phpcs:
        name: WPCS
        runs-on: ubuntu-latest
        outputs:
            phpcs_report_exists: ${{ steps.check_file.outputs.phpcs_json_exists }}
        steps:
            - uses: actions/checkout@v4
            - name: WPCS check
              uses: 10up/wpcs-action@stable
              with:
                  enable_warnings: true
                  standard: 'WordPress'
                  repo_branch: 'main'
                  use_local_config: 'true'
                  only_changed_files: true
                  only_changed_lines: true
                  extra_args: '--report-json=./phpcs.json'
            - id: check_file
              if: always()
              run: |
                  echo "phpcs_json_exists=$(test -f ./phpcs.json && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
            - name: Update summary
              if: always() && steps.check_file.outputs.phpcs_json_exists == 'true'
              run: |
                  npm i -g github:10up/phpcs-json-to-md
                  phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
                  cat phpcs.md >> $GITHUB_STEP_SUMMARY
            - name: Upload PHPCS report
              uses: actions/upload-artifact@v4
              if: always() && steps.check_file.outputs.phpcs_json_exists == 'true'
              with:
                  name: warnings-and-errors-report
                  path: phpcs.md
                  if-no-files-found: ignore

    comment-on-pr:
        needs: phpcs
        runs-on: ubuntu-latest
        if: needs.phpcs.outputs.phpcs_report_exists == 'true' && github.event_name == 'pull_request'
        steps:
            - name: Comment on PR
              uses: actions/github-script@v6
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const artifactLink = `https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}`;
                      const commentBody = `:white_check_mark: PHPCS report is ready! You can download the artifact [here](${artifactLink}).`;
                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: commentBody
                      });
            - name: Fail check
              run: exit 1
